server:
  port: 8150
  servlet:
    context-path: /api/v1/

services:
  olive-insurance-auth-service:
    base-url: ${AUTH_SERVICE_URL}
  olive-insurance-administration-service:
    base-url: ${ADMINISTRATION_SERVICE_URL}
  olive-insurance-settings-service:
    base-url: ${SETTINGS_SERVICE_URL}
  olive-insurance-exploitation-service:
    base-url: ${EXPLOITATION_SERVICE_URL}
  olive-insurance-pricing-service:
    base-url: ${PRICING_SERVICE_URL}

spring:
  application:
    name: dev_olive_insurance_insured_service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Configuration spécifique au développement
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  cloud:
    consul:
      host: ${SPRING_CLOUD_CONSUL_HOST:localhost}
      port: ${SPRING_CLOUD_CONSUL_PORT:8500}
      discovery:
        register: ${SPRING_CLOUD_CONSUL_DISCOVERY_REGISTER:true}
        deregister: ${SPRING_CLOUD_CONSUL_DISCOVERY_DEREGISTER:true}
        health-check-path: ${SPRING_CLOUD_CONSUL_DISCOVERY_HEALTHCHECKPATH:/api/v1/actuator/health}
        prefer-ip-address: ${SPRING_CLOUD_CONSUL_DISCOVERY_PREFER_IP_ADDRESS:true}

  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:1025}
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

# Logs plus détaillés en développement
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    org.springframework.orm.jpa: DEBUG
    sn.zeitune.oliveinsuranceinsured: DEBUG

jwt:
  user:
    public-key: classpath:keys/public-user.pem
    expiration: 900000 # 15 min

  admin:
    public-key: classpath:keys/public-admin.pem
    expiration: 300000 # 5 min

#trusted-services:
#  auth-service: classpath:keys/services/auth-public.pem
#  administration-service: classpath:keys/services/administration-public.pem