package sn.zeitune.oliveinsuranceinsured.app.dtos.responses;

import sn.zeitune.oliveinsuranceinsured.enums.Energie;
import sn.zeitune.oliveinsuranceinsured.enums.Gender;
import sn.zeitune.oliveinsuranceinsured.enums.LicenseCategory;
import sn.zeitune.oliveinsuranceinsured.enums.TypeCarrosserie;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

public record RiskResponse(
        Long id,
        UUID uuid,
        Boolean isFleetMember,
        UUID parentFleetPoliceUuid,
        Integer numAvenant,
        String immatriculation,
        Integer ordre,
        String marque,
        String modele,
        UUID productUuid,
        UUID insuredUuid,
        String driverName,
        Gender driverGender,
        LocalDate driverBirthDate,
        LicenseCategory licenseType,
        String licenseNumber,
        LocalDate licenseIssueDate,
        String licenseIssuePlace,
        Boolean creditDelegation,
        String zone,
        UUID vehicleTypeUuid,
        UUID genreUuid,
        UUID usageUuid,
        LocalDate firstRegistrationDate,
        Energie energie,
        String chassisNumber,
        String engineNumber,
        TypeCarrosserie bodyType,
        Boolean hasTurbo,
        Boolean hasTrailer,
        Boolean isFlammable,
        BigDecimal power,
        BigDecimal tonnage,
        BigDecimal cylinder,
        Integer seatCount,
        UUID attestationNumberUuid,
        UUID formulaPTUuid,
        Integer nbPersonsTransported,
        Integer maxSpeed,
        BigDecimal newValue,
        BigDecimal marketValue,
        Instant createdAt,
        Instant updatedAt,
        sn.zeitune.oliveinsuranceinsured.app.entities.Insured insuredResponse
) {
}